language: cpp

env:
  global:
    - ANDROID_API_LEVEL=17
    - ANDROID_SDK_VERSION=24.0.2
    - ANDROID_NDK_VERSION=9
    - ANDROID_BUILD_TOOLS_VERSION=20.0.0

  matrix:
    - TARGET=ANDROID
    - TARGET=UNIX
    - TARGET=PC
    - TARGET=WIN64
    - TARGET=WM5
    - TARGET=WM5X
    - TARGET=PPC2000
    - TARGET=PPC2003
    - TARGET=PPC2003X
    - TARGET=ALTAIR
    - TARGET=MANUAL

install:
  # General
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install make g++ libsdl-image1.2-dev libboost-dev
      zlib1g-dev libsdl1.2-dev libfreetype6-dev libpng-dev libjpeg-dev
      libcurl4-openssl-dev libxml-parser-perl librsvg2-bin xsltproc
      imagemagick gettext ttf-dejavu

  # PC

  - if [ "$TARGET" = "PC" ]; then
      sudo apt-get install binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686;
    elif [ "$TARGET" = "WIN64" ]; then
      sudo apt-get install binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64;
    fi

  # Android

  - if [ "$TARGET" = "ANDROID" ]; then
      mkdir -p ~/opt;
      sudo apt-get install openjdk-7-jre-headless openjdk-7-jdk ant vorbis-tools;

      if [ `uname -m` = x86_64 ]; then
        sudo apt-get install libncurses5:i386 libstdc++6:i386 zlib1g:i386;
      fi

      wget http://dl.google.com/android/android-sdk_r$ANDROID_SDK_VERSION-linux.tgz;
      wget http://dl.google.com/android/ndk/android-ndk-r$ANDROID_NDK_VERSION-linux-x86_64.tar.bz2;

      tar -xf android-sdk_r$ANDROID_SDK_VERSION-linux.tgz -C ~/opt;
      tar -xf android-ndk-r$ANDROID_NDK_VERSION-linux-x86_64.tar.bz2 -C ~/opt;

      echo 'y' | ~/opt/android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools;
      echo 'y' | ~/opt/android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION,android-$ANDROID_API_LEVEL;
    fi

  # Windows Mobile

  - if [[ "$TARGET" == "WM"* ]] || [[ "$TARGET" == "PPC"* ]] || [ "$TARGET" = "ALTAIR" ]; then
      wget http://spekje.snt.utwente.nl/~roel/cegcc/mingw32ce-mk-2013-04-03-amd64.tar.xz;
      tar -xJf mingw32ce-mk-2013-04-03-amd64.tar.xz -C ~/;
      export PATH="/home/travis/mingw32ce-mk-2013-04-03-amd64/bin:$PATH";
    fi

  # Manual

  - if [ "$TARGET" = "MANUAL" ]; then
      sudo apt-get install --no-install-recommends texlive texlive-latex-extra
        texlive-lang-ukenglish texlive-lang-german texlive-lang-french
        latex-xcolor pgf liblocale-po-perl;
    fi

script:
  # Compile

  - if [ "$TARGET" = "MANUAL" ]; then
      make -j8 TARGET=UNIX manual;
    elif [ "$TARGET" = "ANDROID" ]; then
      make -j8 TARGET=ANDROID;
    else
      make -j8 TARGET=$TARGET everything;
    fi

  # Run unit tests on platforms where possible (Unix)

  - if [ "$TARGET" = "UNIX" ]; then
      make TARGET=$TARGET check;
    fi

notifications:
  email:
    on_failure: change
