language: cpp

env:
  global:
    - secure: QXDgJN/ksHCyNXDcHjQ91FoBmJ4ECnaWHaB5eCfQ6yhVoop3jAXsMGZsY1cNLgahnTNgvEvOhZO8d0ri8ox80wKz9lASxZgRVPzB2jh2WS4k598epnvXA+MQcK+TTuEMYCwZdv/D8/Uj1o79KSnkQ4AlPcGh0Wha3nveoKN9PwI=
    - ANDROID_API_LEVEL=17
    - ANDROID_SDK_VERSION=24.0.2
    - ANDROID_NDK_VERSION=9
    - ANDROID_BUILD_TOOLS_VERSION=20.0.0
    - ANDROID_KEYSTORE=xcsoar-release.keystore
    - ANDROID_KEY_ALIAS=xcsoar-release

  matrix:
    - TARGET=ANDROID
    - TARGET=UNIX
    - TARGET=PC
    - TARGET=WIN64
    - TARGET=WM5
    - TARGET=WM5X
    - TARGET=PPC2000
    - TARGET=PPC2003
    - TARGET=PPC2003X
    - TARGET=ALTAIR
    - TARGET=MANUAL

before_install:
  - sudo apt-get update

  - openssl aes-256-cbc
    -K $encrypted_cd16ea2a7c97_key
    -iv $encrypted_cd16ea2a7c97_iv
    -in xcsoar-release.keystore.enc
    -out xcsoar-release.keystore -d

install:
  # General

  - sudo apt-get install make g++ libsdl-image1.2-dev libboost-dev
      zlib1g-dev libsdl1.2-dev libfreetype6-dev libpng-dev libjpeg-dev
      libcurl4-openssl-dev libxml-parser-perl librsvg2-bin xsltproc
      imagemagick gettext ttf-dejavu

  # PC

  - if [ "$TARGET" = "PC" ]; then
      sudo apt-get install binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686;
    elif [ "$TARGET" = "WIN64" ]; then
      sudo apt-get install binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64;
    fi

  # Android

  - if [ "$TARGET" = "ANDROID" ]; then
      mkdir -p ~/opt;

      wget http://dl.google.com/android/ndk/android-ndk-r$ANDROID_NDK_VERSION-linux-x86_64.tar.bz2;
      tar -xf android-ndk-r$ANDROID_NDK_VERSION-linux-x86_64.tar.bz2 -C ~/opt;
      rm android-ndk-r$ANDROID_NDK_VERSION-linux-x86_64.tar.bz2;

      wget http://dl.google.com/android/android-sdk_r$ANDROID_SDK_VERSION-linux.tgz;
      tar -xf android-sdk_r$ANDROID_SDK_VERSION-linux.tgz -C ~/opt;
      rm android-sdk_r$ANDROID_SDK_VERSION-linux.tgz;

      sudo apt-get install openjdk-7-jre-headless openjdk-7-jdk ant vorbis-tools;

      if [ `uname -m` = x86_64 ]; then
        sudo apt-get install libncurses5:i386 libstdc++6:i386 zlib1g:i386;
      fi

      echo 'y' | ~/opt/android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools;
      echo 'y' | ~/opt/android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION,android-$ANDROID_API_LEVEL;
    fi

  # Windows Mobile

  - if [[ "$TARGET" == "WM"* ]] || [[ "$TARGET" == "PPC"* ]] || [ "$TARGET" = "ALTAIR" ]; then
      wget http://spekje.snt.utwente.nl/~roel/cegcc/mingw32ce-mk-2013-04-03-amd64.tar.xz;
      tar -xJf mingw32ce-mk-2013-04-03-amd64.tar.xz -C ~/;
      export PATH="/home/travis/mingw32ce-mk-2013-04-03-amd64/bin:$PATH";
    fi

  - if [ "$TARGET" = "ALTAIR" ]; then
      sudo apt-get install upx-ucl;
    fi

  # Manual

  - if [ "$TARGET" = "MANUAL" ]; then
      sudo apt-get install --no-install-recommends
        texlive texlive-latex-extra latex-xcolor pgf liblocale-po-perl
        texlive-lang-ukenglish texlive-lang-german texlive-lang-french;
    fi

after_install: sudo apt-get clean

before_script:
  - if [ "$TRAVIS_TAG" ]; then
      export DEBUG=n;
    fi

script:
  # Compile

  - if [ "$TARGET" = "MANUAL" ]; then
      make -j8 TARGET=UNIX manual;

    elif [ "$TARGET" = "ANDROID" ]; then
      if [ "$TRAVIS_TAG" ]; then
        make -j3 TARGET=ANDROID &&
        make -j3 TARGET=ANDROID7 &&
        make -j3 TARGET=ANDROID86 &&
        make -j3 TARGET=ANDROIDMIPS &&
        make -j3 TARGET=ANDROIDFAT output/ANDROIDFAT/bin/XCSoar.apk;
      else
        make -j8 TARGET=ANDROID;
      fi

    elif [ "$TARGET" = "ALTAIR" ]; then
      make -j8 TARGET=ALTAIR output/ALTAIR/XCSoarAltair.zip;

    else
      make -j8 TARGET=$TARGET everything;
    fi

  # Run unit tests on platforms where possible (Unix)

  - if [ "$TARGET" = "UNIX" ]; then
      make TARGET=$TARGET check;
    fi

before_deploy:
  - mkdir -p output/deploy

  # Move results into deploy folder

  - if [ "$TARGET" = "MANUAL" ]; then
      mv output/manual/*.pdf output/deploy;

    elif [ "$TARGET" = "ANDROID" ]; then
      mv output/$TARGET/bin/XCSoar.apk output/deploy/;

    elif [ "$TARGET" = "ALTAIR" ]; then
      mv output/$TARGET/bin/XCSoar.exe output/deploy/XCSoar-$TARGET.exe;
      mv output/$TARGET/XCSoarAltair.zip output/deploy/;

    elif [ "$TARGET" != "UNIX" ]; then
      mv output/$TARGET/bin/XCSoar.exe output/deploy/XCSoar-$TARGET.exe;
    fi

deploy:
  provider: releases
  api_key:
    secure: beqP+DeMLdnu7ieZzlcpoSQVdSVvjzn3GFg/I980Rc77nUtQpw8PHjLSkNm5dw7uoNnQYlK0GwcwKd4e1kuoP77TjUsFnzrtPYvIIGAi1Rp5WCk8Ma0P+R23mrSuwu7aAJt3pUwzObbYsWe9zYQKvL9xQWJuxkQ4u6+OdFEM+oY=
  file: output/deploy/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_failure: change
